// Code generated by hertz generator.

package gpt

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"search-conversa/biz/model/api/gpt"
	servicesgpt "search-conversa/internal/services/gpt"
)

// CreateConversaMethod .
// @router /api/gpt/conversation [POST]
func CreateConversaMethod(ctx context.Context, c *app.RequestContext) {
	resp, err := servicesgpt.CreateConversa(ctx, c)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, err)
	}
	c.JSON(consts.StatusOK, resp)
}

// ConversaMethod .
// @router /api/gpt/conversation [PUT]
func ConversaMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req gpt.ConversaReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(gpt.ConversaResp)

	c.JSON(consts.StatusOK, resp)
}
